---
- name: Install MAVProxy dependencies
  apt: name=python-dev,python-setuptools,python-serial,python-pip,python-lxml
- name: Install MAVProxy pip dependencies
  pip: name=future
- name: Install MAVProxy pip dependencies
  pip: name=pyserial
- name: Install Python 3 MAVProxy dependencies
  apt: name=python3,python3-dev,python3-setuptools,python3-serial,python3-pip
