---
- name: Install mavproxy dependencies
  apt: name=python-dev,python-setuptools,python-serial,python-pip,python-lxml
- name: Install mavproxy pip dependencies
  pip: name=future
- name: Install mavproxy pip dependencies
  pip: name=pyserial
- name: Install mavproxy
  pip: name=mavproxy
- name: Make the run directory
  file: path=/var/log/mavproxy state=directory owner=juju
- name: Copy the service config
  template: src=mavproxy.service dest=/lib/systemd/system/mavproxy.service
- name: Enable mavproxy
  systemd: name=mavproxy daemon_reload=yes enabled=yes masked=no
  